export * from './ping.controller';
export * from './persona-residente.controller';
export * from './residente-persona.controller';
export * from './registro-visitantes-persona.controller';
export * from './residente-registro-visitantes.controller';
export * from './residente.controller';
export * from './registro-visitante.controller';
export * from './persona.controller';
export * from './registro-visitantes-residente.controller';
